"""migration 2

Revision ID: c4aa56adf706
Revises: 38e2166bc76b
Create Date: 2023-11-02 14:12:26.035608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4aa56adf706'
down_revision = '38e2166bc76b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenditures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenditures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenditures_name'), ['name'], unique=False)

    op.create_table('goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goal_name'), ['name'], unique=False)

    op.create_table('incomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incomes_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incomes_name'))

    op.drop_table('incomes')
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goal_name'))

    op.drop_table('goal')
    with op.batch_alter_table('expenditures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenditures_name'))

    op.drop_table('expenditures')
    # ### end Alembic commands ###
